uoForms/App-CANBeWell

package.json
src/LandingPage.css
src/Landingpage.js

add a CSS to control the logo in the landing page to fit the view

Quick forms

---

src/App.js

add user id into cookies to identify the new user

add user id to cookie to identify whether is a new user

---

src/App.js
src/Body/anatomicalView.js
src/Landingpage.js
src/Tests/Tests.js
src/Topics/Topics.js
src/Tracking.js
yarn.lock

1, Implemented the virtual url method to analyze the page view behavior for this single page application
2, stored a serialized json structured user behavior into ga's event label:
label = {
nav: 'body',
user: this.props.userInfo.userID,
gender: this.props.userInfo.gender,
age: this.props.userInfo.age,
language: this.props.userInfo.language,
role: this.props.userInfo.patient_provider,
category: button
}
3. delete useless language click bahavior from events

Modify the sechma of ga

---

package.json
src/App.js
src/Body/anatomicalView.js
src/Landingpage.js
src/Tests/Tests.js
src/Topics/Topics.js
src/Tracking.js
yarn.lock

1. No changes for the frontend layout and rendering method
2. Add device type, os and browser detection function
3 Refactoring the ga event method which is not merged previously
4 us mobile-detect.js to for better detection of mobile devices, this package should be updated frequently for the new hardwares
5 Most of the modification in ./tracking.js

Add mobile detect.js

---

src/App.css
src/App.js

1 disable the all-gender option both provider and patient
2 enlarge the font for the text in body modal, topics and tests details in app.css

Disable all gender option

---

package.json
public/index.html
src/Body/anatomicalView.js
src/Landingpage.js
src/Tracking.js
src/firebase.jsx
yarn.lock

1 Add firebase config in firebase.jsx
2 Add writeClick() function in Tracking.js
3 Click event logged in the same firebase realtime database

Add firebase strorage method

---

.gitignore
src/App.jsx
src/Tracking.js
src/firebase.jsx

Add default user id check to prevent null value

Analytics test

---

src/JSONFolder/HtmlTopic-EN.json

The Jason file for **EN - Topic** updated based on the (May 1 2020 worksheet)

Update Topic-Eng Jason File

---

src/App.css
src/App.jsx

added link for survey button
also, there were some changes for size of info and survey buttons that need to be test

Survey Link added

---

package.json
src/checkBorkenLinks/ParseFiles.js
yarn.lock

bin jia branch

---

package.json
yarn.lock

Revert "bin jia branch"

---

src/App.jsx
src/JSONFolder/HtmlTopic-EN.json
src/JSONFolder/HtmlTopic-FR.json
src/sideBar.js

Covid link updated-Topics-EN & FR
Disabling Black sideBar by commenting the code

JASON File updates

---

src/JSONFolder/HtmlTest-EN.json
src/JSONFolder/HtmlTest-FR.json
src/JSONFolder/HtmlTopic-EN.json
src/JSONFolder/HtmlTopic-FR.json

Updated the json files with new changes

Analytics test 

---

src/App.css
src/App.jsx
src/Button.css

Using the master component to work on the changes

Help button display changes

---

src/JSONFolder/HtmlTopic-FR.json

Fix on FR alphabetical order

---

src/Lang/Lang.json

just checking github review #326 bug

---

src/App.jsx
src/Tracking.js

This Pull Request contains the fixes related to issues 330 & 331.
330 - Database values rewriting recent entry values and also adding new ones simultaneously
331 - Internal Choose Box Gender(5 options display) and Age issue
modified in - App.jsx & Tracking.js
deployment  - Config files (firebase.json , firebase.jsx, firebaserc, config.js and deploy.sh)  are pointing to transgender hosting sites and Transgender DB

Fixing the issues 330 & 331

---

src/Data.js

Now, male and female content will not be shown in tm and tf content anymore.
Pls review the changes

#334 male/female content should not be shown in tm and tf

---

src/Style/Modal.css

Terms of use

---

src/App.jsx

To display transmasculine and transfeminine in french for french part of choose box.
Tested in local.

updated App.jsx - For tf and tm French display

---

.travis.yml
cypress/integration/userActionTests/bodyPage-test.js
cypress/integration/userActionTests/topicPage-test.js
firebase.json
src/Topics/TopicModal.js
src/firebase.jsx

Production deployment related files

prod deployment

---

src/JSONFolder/HtmlTopic-EN.json
src/JSONFolder/HtmlTopic-FR.json

new mental health

---

src/JSONFolder/HtmlTopic-EN.json

Mental-health Issue

---

src/JSONFolder/HtmlTest-EN.json
src/JSONFolder/HtmlTest-FR.json

for "Ultrasound for AAA" topic

broken link on test

---

src/Homescreeneng.js
src/Homescreenfren.js

Add to Home Screen images are not available #446
the problem was because of the version of React, there should be added ".default" after image sources.

home-screen images issue

---

src/Homescreeneng.js
src/Homescreenfren.js
src/JSONFolder/HtmlTopic-EN.json

Home screen images issue

---

.travis.yml
src/Data.js
src/JSONFolder/HtmlTopic-EN.json

1. Duplicates of Bone Health present under topics.
2. Unexpected order under 'Nutrition' or 'Liver/Alcohol/Drugs' modal.

Fixed two bugs

---

src/Landingpage.js
src/index.js

Reverts uoForms/App-CANBeWell#649

Revert "Mobile app issue test1"

---

public/manifest.json
src/LandingPage_EN.js
src/LandingPage_FR.js

Fixing French install application issue

---

src/Data.js
src/JSONFolder/HtmlTopic-EN.json
src/LandingPage.css
src/LandingPage_EN.js
src/LandingPage_FR.js
src/components/bannerSlider.js
src/index.css
src/services/JSON_content_service.js

@rajsaurav4055 Please review and run the code in your device and check on your device before pushing to test.

resizing the screen

---

src/App.css
src/App.jsx
src/Body/Body.js
src/InstructionModal.js
src/LandingPage.css
src/LandingPage_EN.js
src/LandingPage_FR.js
src/Tests/Tests.js
src/Topics/Topics.js
src/index.css

Added home icons to all the pages (Body, Tests, Topics).
Added back buttons to instruction modal where user adds/updates it personal information (to the left on the same line with choose)
Updated the patient button that looks like green button in lp page and put it at the centre
Left aligned the "tap on any body part" text
Updated the ok, I accept the terms button that looks like green button in lp to maintain consistency for buttons

 added icons ,aligned elements and updated button

---

src/App.css
src/App.jsx
src/Body/Body.css
src/Body/Body.js
src/LandingPage_EN.js
src/LandingPage_FR.js
src/Tests/Tests.js
src/index.css

Buttons Enhancement #697

---

public/iCanBeWell_AboutUs.htm
public/iCanBeWell_àproposdenous.htm
public/staticpages_style.css

Making UI changes in About us & Privacy page

---

src/Tests/Tests.js

Fixing enter issue on Test page

---

public/iCanBeWell_AboutUs.htm

https://github.com/uoForms/App-CANBeWell/issues/769
https://github.com/uoForms/App-CANBeWell/issues/770

made changes for aboutUs page to add feedback on the top too

---

public/iCanBeWell_AboutUs.htm

change heading to Votre avis at the bottom as well

---

public/iCanBeWell_PrivacyPolicy.htm

Back button in french

---

public/iCanBeWell_AboutUs.htm

https://github.com/uoForms/App-CANBeWell/issues/779

made changes for translation issue when switching between pages

---

src/Lang/Lang.json

https://github.com/uoForms/App-CANBeWell/issues/788

made changes to add french text while hovering over kidney icon

---

src/Body/Body.css

Reverts uoForms/App-CANBeWell#801

Revert "made changes to make body icons of same size"

---

src/App.css

made changes for kidney all topics icon

---

src/App.css

Reverts uoForms/App-CANBeWell#806

Revert "made changes for kidney all topics icon"

---

public/iCanBeWell_CheckYourSymptoms.htm
public/staticpages_style.css
src/App.css
src/LandingPage.css
src/Style/custom.scss
src/Tests/Tests.js
src/Topics/TopicModal.js
src/Topics/Topics.js
src/index.css

1. Added underline to clickable links in Check Your Symptoms (EN) page.
2. Changed all #27AAE1 to #0089B5 (part of pull request #823)

Minor fixs & Changed all #27AAE1 to #0089B5

---

public/iCanBeWell_CheckYourSymptoms.htm
public/iCanBeWell_CheckYourSymptoms_FR.htm
public/iCanBeWell_NoFamilyMD_NP_FR.htm
src/firebase.jsx

Changes:
1. Spelling on English Check Your Symptoms page;
2. Back buttons for both pages (Sans MD Famille/IP and Vérifier vos symptômes) now goes to the French Landing page;
3. Sans MD Famille/IP HTML page title changed to: "Je n’ai pas de médecin de famille ou d'infirmière praticienne" (might need to adjust margin);
4. Sans MD Famille/IP page: Ontario and Quebec buttons how have correct links.
**Issue: Sans MD Famille/IP and No Family MD/NP HTML pages: buttons for Provinces on phone still need to be aligned left.**

Bug fixes corresponding to May 10th meeting

---

.firebaserc
src/firebase.jsx

Deployment to Production

---

firebase.json

Testing Production

---

package.json
public/iCanBeWell_NoFamilyMD_NP_FR.htm

Pulkit dev01

---

package.json
src/App.jsx
src/Body/anatomicalView.js
src/LandingPage_EN.js
src/LandingPage_FR.js
src/Lang/Lang.json
src/Topics/Topics.js
src/components/DialogBox.js
src/constants.js
yarn.lock

This PR adds a dialog box which prompts the user to choose to give a feedback , this will only occur as long as the person does not click on the agree button.

feature_861 : Add new dialog box as per requirement
